### ISSUE TITLE
Handling tables with column `type`

### ISSUE THREAD

**Issue by carterhimmel** [Jasperav/Catalytic#35]
Howdy! 

With `catalytic_table_to_struct`, is it possible to rename column names? I'm messing around with a very large database with various `type` columns.

How can I rename them to, say, `r#type`?

**Comment by carterhimmel** [comment]
I don't think the code for this exists, but it could be implemented on `StructField`.
By adding `column_name` to `StructField`, I believe the name of the column on the struct could be changed.
```rs
struct Trans;

impl Transformer for Trans {
    fn struct_field(&self, _struct_table: StructTable, column_name: &str) -> StructField {
        StructField {
            json: None,
            is_nullable: true,
            attributes: Default::default(),
			column_name: if column_name == "type" {
				"r#type".to_string()
			} else { column_name }
        }
    }
}
```

https://github.com/Jasperav/Catalytic/blob/026feabd928ecf67572d468810d0b3291fa94ff5/catalytic_table_to_struct/src/column_mapper.rs#L104
Then, the above line can be rewritten to
```rs
 let ident = format_ident!("{}", struct_field.column_name); 
```

However, this doesn't consider the distinction between the column name in the database versus the struct.

**Comment by Jasperav** [comment]
Hey @carterhimmel, thanks for reporting this issue. I understand the issue you are facing, and you are correct this can be customized through StructField. I can have a look next week since I am now on holiday :).

**Comment by carterhimmel** [comment]
Sounds good! I will say, I was able to get it done but a few more misc. problems arose.
https://github.com/Jasperav/Catalytic/compare/master...trufflehq:catalytic:feat/column_name

**Comment by Jasperav** [comment]
@carterhimmel I just published a new version of this library with custom field names (https://github.com/Jasperav/Catalytic/pull/36), let me know if there are any issues!

**Comment by carterhimmel** [comment]
Thank you! Will get around to testing it this week! :)
