### ISSUE TITLE
`catalytic_table_to_struct` can't make some materialized views

### ISSUE THREAD

**Issue by carterhimmel** [Jasperav/Catalytic#37]
At work, we have a table `api_keys_by_id`, with a materialized view `api_keys_by_orgId`. However, when `catalytic_table_to_struct` creates the MV, it doesn't do much. Here's the generated code, shortened a little:
```rs
// Generated file
pub const SELECT_ALL_QUERY: &str = "select  from api_keys_by_orgId";
pub const SELECT_ALL_COUNT_QUERY: &str = "select count(*) from api_keys_by_orgId";
pub const SELECT_UNIQUE_QUERY: &str = "select  from api_keys_by_orgId where ";
#[derive(
    scylla :: FromRow, scylla :: ValueList, catalytic_macro :: Mirror, Debug, Clone, PartialEq,
)]
pub struct ApiKeysByOrgId {}
impl ApiKeysByOrgId {
    pub fn primary_key(&self) -> PrimaryKeyRef {
        PrimaryKeyRef {}
    }
    pub fn primary_key_owned(&self) -> PrimaryKey {
        self.primary_key().into_owned()
    }
    pub fn into_primary_key_owned(self) -> PrimaryKey {
        PrimaryKey {}
    }
}
```

This is the `get_columns` function:

```cql
select
    column_name,
    kind,
    position,
    type as data_type
from system_schema.columns
where keyspace_name = 'spore'
and table_name = 'api_keys_by_orgId';
```

and it's response: 
![image](https://github.com/Jasperav/Catalytic/assets/45381083/cfea87c3-7261-416e-8bf6-ec6dc0a3fbca)

**Comment by Jasperav** [comment]
Hmm I can not reproduce this right away, could you give me the table definitions (as small as possible which replaces the problem)?.

**Comment by Jasperav** [comment]
@carterhimmel Any chance you already have the cql file so I can reproduce it?

**Comment by carterhimmel** [comment]
Hmm, I'm afraid not. Let me look into this a little more

**Comment by Jasperav** [comment]
@carterhimmel You can reopen this issue if there is any reproduction path :)
