### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by DanielHe4rt** [Jasperav/Catalytic#40]
Hey! I'm Daniel, Developer Advocate at ScyllaDB and I truly liked your project! It's my first time trying Rust and the way that Catalytic works is fascinating! 

I'm wondering if there's any way of me contributing to docs improvements on this project. I mean, it's a great tool but there's not so much information on how to use it and for me from a few hours ago it would be real important :p

In any case I'm here to offer some help to struct some cool documentation for this project! What do you think?

Cheers!

**Comment by Jasperav** [comment]
Hey @DanielHe4rt thanks for your kind words! I know Catalytic is used in production by a few and I actively maintain it, hearing that you are checking it out flatters me :). Docs can be improved yes, I wrote a blog post how to use it here: https://www.scylladb.com/2022/02/15/introducing-catalytic-an-orm-designed-for-scylladb-and-cassandra-written-in-rust/. There is also a small section in the readme which describes how to use it, but maybe not sufficient for people who wants to try it out.

Which parts would you say needs the most attention? PR's are always welcome!

Thanks!

**Comment by DanielHe4rt** [comment]
I saw this article but I didn't understood how things work on the details... 

Maybe some snippets of usage on the main README.md should be a good improvement. Jump into the project examples is a good approach, but since we can just show what matters in the first moment it can be way better. 

What do you think?

**Comment by Jasperav** [comment]
These sounds like good additions, especially to get new users started! If you want to contribute, please open a PR and I would be happy to look at it :)
