### ISSUE TITLE
User defined types (UDT) Types are supported?

### ISSUE THREAD

**Issue by lnxdxtf** [Jasperav/Catalytic#41]
[SCYLLA-UDT](https://rust-driver.docs.scylladb.com/stable/data-types/udt.html)
I'm creating the udt types on build and specify the struct

UDT = Team, Teams and League
~build.rs
![image](https://github.com/Jasperav/Catalytic/assets/90481507/49ed1338-80cc-496f-a865-94e6b9081837)
![image](https://github.com/Jasperav/Catalytic/assets/90481507/0c097312-bd96-4df0-ab6f-03bbee7b2188)
src/types_helper/betwise.rs
![image](https://github.com/Jasperav/Catalytic/assets/90481507/6adf5312-a211-4ab3-8753-0a8b479645e6)

Do I need to use the text type on creation of table for columns that use UDT?

**Comment by Jasperav** [comment]
Currently UDT types are not supported, as well as Lists, tuples and a few other types. For the complete list of supported types, check out: https://github.com/Jasperav/Catalytic/blob/6b74c52a4926d5aee7034a2b545befcbb61b08b2/catalytic/src/table_metadata.rs#L66. Note that you CAN use JSON types with auto serialize/deserialize, I am not sure about what benefits using UDT's have over JSON types. For an example, check out: https://github.com/Jasperav/Catalytic/blob/6b74c52a4926d5aee7034a2b545befcbb61b08b2/catalytic_table_to_struct/example/build.rs#L34.

**Comment by lnxdxtf** [comment]
Thanks a bunch for the quick reply and the insights! Using JSON types with auto serialize/deserialize sounds like a neat idea. I'm gonna dive into that and check out the example you mentioned. Really helpful stuff!
🤠
