### ISSUE TITLE
RUSTSEC-2021-0141: dotenv is Unmaintained

### ISSUE THREAD

**Issue by fatihergin** [Jasperav/Catalytic#46]
Hi,

It looks dotenv crate is no longer maintained which cargo audit complaints about.
Hopefully there is an up to date fork [dotenvy](https://crates.io/crates/dotenvy).

Is it possible to replace it with the maintained one? 

People can't get answer to their questions(https://github.com/dotenv-rs/dotenv/issues/74, https://github.com/dotenv-rs/dotenv/issues/87) about future of this crate.

And, thanks for your valuable effort.

**Comment by Jasperav** [comment]
Thanks for your comment, I didn't knew it was unmaintained :) I switched to `dotenvy` and upgraded this crate to be clippy compatible with Rust 1.75 as well.
